### ISSUE TITLE
Starting host software

### ISSUE THREAD

**Issue by indian22** [hradec/chemshapes#1]
Hy hradec,
i have his problem: when i click on “Click here to run Chemshapes Host Software.cmd” this message appear:

c:\host>._debug_env_w32\python27\python.exe draft.py
traceback <most recent call last>:
File "draft.py", line 16, in <module>
import glSVG
ImportError: No module named glSVG

I don't know what is it!.

Thank you...great work!!!

Francesco

**Comment by hradec** [comment]
hoo... ok... thanks for that!! I forgot to submit something... hold tight!!!

-H
blog http://hradec.blogspot.com/   home http://hradec.com/

**Comment by hradec** [comment]
fixed

**Comment by hradec** [comment]
This damn pearltrees website was supposed to send just an invitation to the
3 friends I selected from my contact list, But it seems like it sent it out
to EVERYONE!!!

So, my sincere apologies... It won't happen again!

-H
blog http://hradec.blogspot.com/   home http://hradec.com/
