### ISSUE TITLE
Loading mesh

### ISSUE THREAD

**Issue by indian22** [hradec/chemshapes#3]
Hy hradec,
still there....i download the fixed version, there are no problem to start software, but when i load the stl or obj file it doesn't start...this is the log description:

Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:42 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:46 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:58 2011 >> reading text fileC:/hradec-chemshapes-b7aeddb/host/meshes/polyholes2.stl
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: 'normal'
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: Traceback (most recent call last):
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: File "C:\hradec-chemshapes-b7aeddb\host\glViewport__init__.py", line 316, in paintGL
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: self.s['normal'].bind()
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: KeyError
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: :
Mon Jul 25 13:08:59 2011 >> PYTHON EXCEPTION: 'normal'

Thanks

Francesco

**Comment by hradec** [comment]
Sorry about that... I don't have windows at home, so I fixed on OSX... I just tested today in Windows at work and got the same error as you. Just fixed, so it should be ok now... 

Could you give it a try and let me known here so I can close this ticker, plz? 

thanks...

**Comment by indian22** [comment]
perfect,
now works correctly!!

Thanks

Francesco

**Comment by hradec** [comment]
One question... When u load a model, does it show up white or red?

**Comment by indian22** [comment]
it appears red like in your video.

bye

Francesco

**Comment by hradec** [comment]
awesome! closing the issue! thanks!
